collections:
  - name: "sozluk"
    label: "Sözlük"
    description: "Sözlük - kelime ekle"
    folder: "src/content/docs/sozluk/" 
    create: true
    fields: 
      - { label: "Sözcük", name: "title", widget: "string" }
      - { label: "Tarih", name: "lastUpdated", widget: "datetime", required: false }
      - label: "Eş anlamlılar"
        name: "synonyms"
        widget: "list"
        required: false
        allow_add: true
      - label: "İlgi"
        name: "relations"
        widget: "relation"
        collection: "sozluk"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
        required: false
      - { label: "İçerik", name: "body", widget: "markdown" }

backend:
  name: github
  repo: ulughann/sozluk
  open_authoring: true
  auth_scope: repo

publish_mode: editorial_workflow
media_folder: "static/images/uploads" 
public_folder: "/images/uploads"