collections:
  - name: "sozluk"
    label: "Sözcükler"
    description: "Sözlük - sözcük ekle"
    folder: "src/content/docs/sozluk/" 
    create: true
    fields: 
      - { label: "Sözcük", name: "title", widget: "string" }
      - { label: "Sözcük türü", name: "type", widget: "select", multiple: true, options: ["isim", "fiil", "sıfat", "bağlaç", "edat", "zamir", "ünlem", "zarf", "diğer"], default: "isim" }
      - { label: "Kategori", name: "category", widget: "select", multiple: true, options: ["Doğal bilimler", "Sayı bilim", "Sosyal bilimler", "Yazın bilim", "Sanat", "Günlük yaşam", "Yazılım ve teknoloji", "Bitki bilim", "Tıp", "Tarım", "Hukuk"], default: [] }
      - { label: "Tarih" , name: "lastUpdated", widget: "datetime", required: false, default: '{{now}}' }
      - label: "Eş anlamlılar"
        name: "synonyms"
        widget: "list"
        required: false
        allow_add: true
      - label: "Varyantlar"
        name: "variants"
        widget: "list"
        required: false
        allow_add: true
      - { label: "İçerik", name: "body", widget: "markdown" }

  - name: "ekler"
    label: "Ekler"
    description: "Ekler - ek ekle"
    folder: "src/content/docs/ekler/"
    create: true
    fields:
      - { label: "Ek", name: "title", widget: "string" }
      - { label: "İçerik", name: "body", widget: "markdown" }

  - name: "yazilar"
    label: "Yazılar"
    description: "Yazılar - yazı ekle"
    folder: "src/content/docs/yazilar/"
    create: true
    fields:
      - { label: "Yazı", name: "title", widget: "string" }
      - { label: "Tarih", name: "lastUpdated", widget: "datetime", required: false }
      - { label: "Açıklama", name: "description", widget: "text", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }

  - name: "pt"
    label: "Ön Türkçe"
    description: "Ön Türkçe - kelime ekle"
    folder: "src/content/docs/pt/" 
    create: true
    fields: 
      - { label: "Sözcük", name: "title", widget: "string" }
      - { label: "Sözcük türü", name: "type", widget: "select", multiple: true, options: ["isim", "fiil", "sıfat", "bağlaç", "edat", "zamir", "ünlem", "zarf", "diğer"], default: "isim" }
      - label: "Varyantlar"
        name: "variants"
        widget: "list"
        required: false
        allow_add: true
      - { label: "İçerik", name: "body", widget: "markdown" }

backend:
  name: github
  repo: ulughann/sozluk
  open_authoring: true
  auth_scope: repo

slug:
  encoding: "unicode"
  clean_accents: false
  sanitize_replacement: "-"
  trim: false

publish_mode: editorial_workflow
media_folder: "static/images/uploads" 
public_folder: "/images/uploads"