collections:
  - name: "sozluk"
    label: "Sözlük"
    description: "Sözlük - kelime ekle"
    folder: "src/content/docs/sozluk/"
    create: true
    slug:
      encoding: "unicode"
      clean_accents: true
      sanitize_replacement: "-"
    fields:
      - label: "Sözcük"
        name: "title"
        widget: "string"
      - label: "Tarih"
        name: "lastUpdated"
        widget: "datetime"
        required: false
      - label: "Eş anlamlılar"
        name: "synonyms"
        widget: "list"
        required: false
        allow_add: true
      - label: "Varyantlar"
        name: "variants"
        widget: "list"
        required: false
        allow_add: true
      - label: "İçerik"
        name: "body"
        widget: "markdown"
  - name: "ekler"
    label: "Ekler"
    description: "Ekler - ek ekle"
    folder: "src/content/docs/ekler/"
    create: true
    fields:
      - label: "Ek"
        name: "title"
        widget: "string"
      - label: "Tarih"
        name: "lastUpdated"
        widget: "datetime"
        required: false
      - label: "İçerik"
        name: "body"
        widget: "markdown"
  - name: "yazilar"
    label: "Yazılar"
    description: "Yazılar - yazı ekle"
    folder: "src/content/docs/yazilar/"
    create: true
    slug:
      encoding: "unicode"
      clean_accents: true
      sanitize_replacement: "-"
    fields:
      - label: "Yazı"
        name: "title"
        widget: "string"
      - label: "Tarih"
        name: "lastUpdated"
        widget: "datetime"
        required: false
      - label: "Açıklama"
        name: "description"
        widget: "text"
        required: false
      - label: "İçerik"
        name: "body"
        widget: "markdown"
  - name: "pt"
    label: "Ön Türkçe"
    description: "Ön Türkçe - kelime ekle"
    folder: "src/content/docs/pt/"
    create: true
    slug:
      encoding: "unicode"
      clean_accents: true
      sanitize_replacement: "-"
    fields:
      - label: "Sözcük"
        name:
      - label: "Sözcük tipi"
        name: "type"
        widget: "select"
        options: ["Fiil", "Ad", "Sıfat", "Diğer"]
      - label: "Eş anlamlılar"
        name: "synonyms"
        widget: "list"
        required: false
        allow_add: true
      - label: "Varyantlar"
        name: "variants"
        widget: "list"
        required: false
        allow_add: true
      - { label: "İçerik", name: "body", widget: "markdown" }


backend:
  name: github
  repo: ulughann/sozluk
  open_authoring: true
  auth_scope: repo

publish_mode: editorial_workflow
media_folder: "static/images/uploads" 
public_folder: "/images/uploads"
