collections:
  - name: "sozluk"
    label: "Sözcükler"
    description: "Sözlük - sözcük ekle"
    folder: "src/content/docs/sozluk/" 
    create: true
    fields: 
      - { label: "Sözcük", name: "title", widget: "string" }
      - { label: "Açıklama", name: "description", widget: "compute", required: false, value: 'Öz Türkçe Sözlük : {{fields.title}}, {{fields.title}} ne demek?' }
      - { label: "Sözcük türü", name: "type", widget: "select", multiple: true, options: ["isim", "fiil", "sıfat", "bağlaç", "edat", "zamir", "ünlem", "zarf", "diğer"], default: "isim" }
      - { label: "Kategori", required: false, name: "category", widget: "select", multiple: true, options: ["Doğal bilimler", "Sayı bilim", "Sosyal bilimler", "Yazın bilim", "Sanat", "Günlük yaşam", "Yazılım ve teknoloji", "Bitki bilim", "Tıp", "Tarım", "Hukuk"], default: [] }
      - { label: "Tarih" , name: "lastUpdated", widget: "datetime", required: false, default: '{{now}}' }
      - label: "Eş anlamlılar"
        name: "synonyms"
        widget: "list"
        required: false
        allow_add: true
      - label: "Varyantlar"
        name: "variants"
        widget: "list"
        required: false
        allow_add: true
      - { label: "İçerik", name: "body", widget: "markdown" }

  - name: "ekler"
    label: "Ekler"
    description: "Ekler - ek ekle"
    folder: "src/content/docs/sozluk/-ekler/"
    create: true
    fields:
      - { label: "Ek", name: "title", widget: "string" }
      - { label: "İçerik", name: "body", widget: "markdown" }

  - name: "yazilar"
    label: "Yazılar"
    description: "Yazılar - yazı ekle"
    folder: "src/content/docs/yazilar/"
    create: true
    fields:
      - { label: "Yazı", name: "title", widget: "string" }
      - { label: "Tarih", name: "lastUpdated", widget: "datetime", required: false }
      - { label: "Açıklama", name: "description", widget: "text", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }

  - name: "pt"
    label: "Ön Türkçe"
    description: "Ön Türkçe - kelime ekle"
    folder: "src/content/docs/pt/" 
    create: true
    fields: 
      - { label: "Sözcük", name: "title", widget: "string" }
      - { label: "Açıklama", name: "description", widget: "compute", required: false, value: 'Ön Türkçe Sözlük : {{fields.title}}' }
      - { label: "Sözcük türü", name: "type", widget: "select", multiple: true, options: ["isim", "fiil", "sıfat", "bağlaç", "edat", "zamir", "ünlem", "zarf", "diğer"], default: "isim" }
      - label: "Varyantlar"
        name: "variants"
        widget: "list"
        required: false
        allow_add: true
      - { label: "İçerik", name: "body", widget: "markdown" }
      - {label: "Türkçe" name: "tr" widget: "string" required: false}
      - { label: "Azerice", name: "az", widget: "string", required: false }
      - { label: "Türkmence", name: "tk", widget: "string", required: false }
      - { label: "Gagavuzca", name: "gag", widget: "string", required: false }
      - { label: "Çuvaşça", name: "chv", widget: "string", required: false }
      - { label: "Tuvaca", name: "tyv", widget: "string", required: false }
      - { label: "Hakasça", name: "kjh", widget: "string", required: false }
      - { label: "Kazakça", name: "kk", widget: "string", required: false }
      - { label: "Kırgızca", name: "ky", widget: "string", required: false }
      - { label: "Kırım Tatarcası", name: "crh", widget: "string", required: false }
      - { label: "Volga Tatarcası", name: "vot", widget: "string", required: false }
      - { label: "Karakalpakça", name: "kaa", widget: "string", required: false }
      - { label: "Özbekçe", name: "uz", widget: "string", required: false }
      - { label: "Uygurca", name: "ug", widget: "string", required: false }
      - { label: "Altayca", name: "alt", widget: "string", required: false }
      - { label: "Yakutça", name: "sah", widget: "string", required: false }
      - { label: "Tatarca", name: "tt", widget: "string", required: false }
      - { label: "Başkurtça", name: "ba", widget: "string", required: false }

  - name: "pt-ekler"
    label: "Ön Türkçe Ekler"
    description: "Ön Türkçe Ekler - ek ekle"
    folder: "src/content/docs/pt/-ekler/"
    create: true
    fields:
      - { label: "Ek", name: "title", widget: "string" }
      - { label: "İçerik", name: "body", widget: "markdown" }
    

backend:
  name: github
  repo: ulughann/sozluk
  open_authoring: true
  auth_scope: repo

slug:
  encoding: "unicode"
  clean_accents: false
  sanitize_replacement: "-"
  trim: false

publish_mode: editorial_workflow
media_folder: "static/images/uploads" 
public_folder: "/images/uploads"